name: logdna
description: A simple logdna client for Flutter. Push logs directly to your LogDNA dashboard in a few lines of code.
version: 1.2.2
repository: https://github.com/aligorithm/logdna_flutter
issue_tracker: https://github.com/aligorithm/logdna_flutter/issues
homepage: https://aligorithm.i.ng

environment:
  sdk: ">=3.0.6 <4.0.0"

dependencies:
  http: ^1.2.1
